/** Demo wishlist rows when the API returns an empty list. */
export const MOCK_WISHLIST = [
  {
    id: "wish-mock-1",
    target_id: "creator-mock-ria",
    target_type: "influencer",
    name: "Ria Kapoor",
    username: "ria.creates",
    handle: "ria.creates",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
    city: "Mumbai",
    state: "Maharashtra",
    niches: ["Fashion", "Lifestyle"],
    _mock: true,
  },
  {
    id: "wish-mock-2",
    target_id: "brand-mock-veda",
    target_type: "brand",
    name: "Veda Organics",
    company: "Veda Organics",
    avatar: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=200&q=80",
    city: "Delhi",
    state: "Delhi",
    industry: "Beauty",
    _mock: true,
  },
  {
    id: "wish-mock-3",
    target_id: "prod-mock-lens",
    target_type: "production",
    name: "Aarav Lens",
    production_category_label: "Camera Team",
    production_role: "Cameraman",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    city: "Mumbai",
    state: "Maharashtra",
    _mock: true,
  },
  {
    id: "wish-mock-4",
    target_id: "creator-mock-dev",
    target_type: "influencer",
    name: "Dev Sharma",
    username: "devtech",
    handle: "devtech",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    city: "Bangalore",
    state: "Karnataka",
    niches: ["Technology", "Gadgets"],
    _mock: true,
  },
];
